/*
	Given two strings s and t which consist of only lowercase letters.

	String t is generated by random shuffling string s and then add one more letter at a random position.

	Find the letter that was added in t.

	Example:

	Input:
	s = "abcd"
	t = "abcde"

	Output:
	e

	Explanation:
	'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> v(26);
        for(int i = 0;i < s.size();i++){
            v[s[i] - 'a'] ++;
            v[t[i] - 'a'] --;
        }
        v[t[t.size()-1] - 'a']--;
        int i = 0;
        for(;i<26;i++){
            if(v[i] != 0)   break;
        }
        return 'a' + i;
    }
};

class Solution {
public:
    char findTheDifference(string s, string t) {
        int ans = 0;
        for(int i = 0;i < s.size();i++){
            ans -= s[i];
            ans += t[i];
        }
        ans += t[t.size()-1];
                
        return ans;
    }
};